### ISSUE TITLE
Change arrows direction in accordion

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpa-apgf#118]
To have a seemless experience with the viewer. Set ***arrow up*** for ***open*** accordion and ***arrow down*** for ***close accordion***. Need to be done everywhere in the author (forms, summary, ...)

**Author**
![arrowAuthor.gif](https://images.zenhubusercontent.com/5734cfffbf93871ccd9af108/ffe0714c-db98-4852-aca6-eff52bba368f)

**Viewer**
![arrowViewer.gif](https://images.zenhubusercontent.com/5734cfffbf93871ccd9af108/a547eb19-e9cb-46be-90ba-329c65d9b068)

**Comment by jolevesq** [comment]
If we look at Atom how the arrrow work, they work the same way as the form. What do we decide: follow the viewer or follow or the standard (Atom, [jqueryUi](https://jqueryui.com/accordion/).

**Comment by ChrisLatRNCan** [comment]
Maybe we should ask viewer team why they have chosen this behaviour in the first place.
Personnaly, I prefer the jquery way of doing things.
