### ISSUE TITLE
Bilingual UI

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpa-apgf#13]
As a user,
I want to be able to use the tool in the official language of my choice (french or English),
So that I can edit my map

**Comment by yblain** [comment]
Two schemas will be required. 

Needs more analys between i18n and description tags inside the schema.

**Comment by ChrisLatRNCan** [comment]
The [fgpa-schema-splitter](https://github.com/ChrisLatRNCan/fgpa-schema-splitter) is creating schemas in both English and French. Other languages could eventually be added.

**Comment by jolevesq** [comment]
Now we have language switching capabilities inside the viewer. It tooks data-av-languages and set schema, form and configuration. Related to #46
