### ISSUE TITLE
Summary doesnt update when lods is deleted

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpa-apgf#139]
When we delete one of the lods, a validation error occurs inside tile schema because lods id is missing. When we hit validate, the summary panel doesn't reflect the problem!

![Screen Shot 2018-01-19 at 7.35.46 AM.png](https://images.zenhubusercontent.com/5695178c638e718c99600115/ee9b55e5-c17a-4965-8799-db0fad6e8874)

**Comment by ChrisLatRNCan** [comment]
For whatever reason the extentSet ID and the LOD id are not part of the form object
![image](https://user-images.githubusercontent.com/16193004/35153099-1e4e0a1e-fcf3-11e7-8a6f-b6ad585ef9e7.png)

**Comment by ChrisLatRNCan** [comment]
The only way I see is to create a new function that check for an undefined values in the model. 

![image](https://user-images.githubusercontent.com/16193004/35153655-5e426e2e-fcf5-11e7-8fd6-cfd07601d7a3.png)

**Comment by ChrisLatRNCan** [comment]
#142
