### ISSUE TITLE
Selecting Plugins in Side Menu Items does not reveal the Plugin Link section in Preview

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#148]
The problem is that plugins also need to be called in the viewer's HTML page, but maybe the **Plugin Links** section header should appear (when selected) even if there are no plugins called in the HTML page.

![plugins](https://user-images.githubusercontent.com/2006029/35169272-f765f376-fd29-11e7-9afa-40ebd24e065d.png)

**Comment by jolevesq** [comment]
In version 3.1 they change the way it works. Plugins needs to be added to the map header (css and js) and inside the property rv-plugins ofdiv map. Plugins sections is always there even if there is no plugins available.
