### ISSUE TITLE
Create lookup table for AGOL config file to the viewer

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpa-apgf#160]
Use AGOL file and transfert it to viewer format. First, we need to create a lookup table to see what can be map.

**Comment by james-rae** [comment]
Some of the comments on https://github.com/fgpv-vpgf/fgpv-vpgf/issues/398 might be of some help, though it's outdated.

**Comment by jolevesq** [comment]
### From AGOL WebMap

For basemaps we can extract those informations:

Schema "baseMaps[]" | AGOL "baseMap.baseMapLayers[]"
---------|-------
id (string) | generate random one
name (string) | title (string)
description (string) |   need to get from service url
thumbnailUrl (string) | need to get from service url
altText (string) | Use title
attribution (object) | use service default
tileSchemaId (id) | use service to get information for lods, wkid to generate a proper tileschema if not exist and use the id
layers (array) | ---
layers - url | url
layers opacity | opacity
layers - id | id
layers - layerType | layerType

In AGOL WebMap you can't have a collection of basemaps. You only have one but it can be an array of basemaps. So we use the array to set one basemap in our schema.

For feature layers we can extract those informations:

Schema "layers[]" | AGOL "oprationalLayers[]"
---------|-------
id | id
name | title
nameField | ---
url | url
refreshInterval | refreshInterval
metadataUrl | ---
catalogueUrl | ---
layerType | layerType (ArcGISFeatureLayer)
toggleSymbology | ---
tolerance | ---
extent | ---
controls | ---
disabledControls | ---
state.opacity | opacity
state.visibility | visibility
state.boundingBox | ---
state.query | ---
state.snapshot | mode
state.hovertips | ---
--- | layerDefinition (minScale, maxScale)
table.columns.filters|  layerDefinition (definitionExpression)

Other info we can extract 
Schema  | AGO
---------|-------------------
ui.about.content | description, snippet, title
map.extentSets[].spatialReference.wkid | spatialReference.wkid
map.extentSets[].default | extent[]

**Comment by jolevesq** [comment]
### From AGOL WebApp
