### ISSUE TITLE
Link Preview with validation

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpa-apgf#166]
We want the Preview button to be available only when there's no more error after running the validation process. So, by default the button is disabled until the validation process has been executed and no more error has been identified.  Also, had content to config-AuthorA so the validation process will execute without error (demo purpose).

**Comment by jolevesq** [comment]
At the same time, can you disable expand and collapse until first validation has been made. If not, when user click on them nothing happen because the tree doesn't exist

**Comment by ChrisLatRNCan** [comment]
Also, disable EXPAND-COLLAPSE if validation has not be done yet
