### ISSUE TITLE
Create initial forms in ASF

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpa-apgf#23]
Create forms for each section of the schema. Forms will be saved into individual json files.
Will produce some mockups aside

- [x] **General**

- [x] **UI**

- [x] **Services**

- [x] **Map**

**Comment by yblain** [comment]
UI and services are targeted first

**Comment by ChrisLatRNCan** [comment]
Raw forms can now be generated. Still need improvements.
