### ISSUE TITLE
Create file for Atlas old GCViz application

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpa-apgf#243]
Create files to migrate old GCViz application to the new viewer. In the process, identify problem or bug who made use of the authoring tool not effective.

Message from Patricia

Hi Johann and Christian,

The last two conversions from GCViz to FGPV are:
1.	Clean Energy Resources and Projects (in [English](http://atlas.gc.ca/cerp-rpep/en/) and [French](http://atlas.gc.ca/cerp-rpep/fr/))
2.	Geochronology (in [English](http://atlas.gc.ca/geochron/en/) and [French](http://atlas.gc.ca/geochron/fr/))

The one I would like to start with is the Clean Energy Resources and Projects map.

All of the services except for the basemap are in this folder:
http://geoappext.nrcan.gc.ca/arcgis/rest/services/Energy

The interactive map has a complex legend and a large number of layers.

Legend structure:
•	Clean Power Generation
o	 
•	Major Clean Energy Projects (planned or under construction)
o	 
•	Small-scale and Distributed Generation
•	Carbon Capture and Storage Facilities
•	Bioheat Generation Facilities
•	Clean Energy Test Centres
•	Geothermal Heating Facilities
•	Clean Technology Incubators and Accelerators
•	Research, Development and Demonstration Projects
•	Biomass Resource Potential
o	 
•	Geothermal Resource Potential
o	 
•	Hydro Reservoir Resource Potential
o	 
•	River Current Resource Potential
•	Solar Energy Resource Potential
o	 
•	Tidal Energy Resource Potential
•	Uranium Resource Occurrences
•	Wave Energy Resource Potential
o	 
•	Wind Energy Resource Potential

I will be in the office Monday (19th) and Tuesday (20th) next week and Thursday (29th) the following week if you would like to discuss this further.

Cheers,
Patricia

**Comment by ChrisLatRNCan** [comment]
Je fais le français
