### ISSUE TITLE
Cannot display help files in the Preview map

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#273]
Cannot display help files in the Preview map because the viewer requests them from the fgpa distribution under `./samples/help/` but the author sets the default Help folder name to "default" `./samples/help/default`

### Help File
**Help properties**
    Folder Name 
    [default]
_Help folder name who contain the help description and images_

**Comment by jolevesq** [comment]
We can't show the help inside preview because we don't have access to help folder for the viewer. We can copy help folder and put it inside default but if user change to it's own help, it won't show it.

We will add a note to the help folder selection to specify this cannot be test inside preview
