### ISSUE TITLE
Open user selected config file on load by passing URL parameter

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#290]
Add the option of opening a user selected config file on load by passing a URL parameter with the file name

e.g. /fgpa/samples/fgpv-author.html **?filename=my_file.json**

**Comment by jolevesq** [comment]
Related to #292

**Comment by jolevesq** [comment]
.../fgpv-author.html?filename=http://localhost:6001/samples/config/config-sample.json

.../fgpv-author.html?template=canada-world-fr.json
