### ISSUE TITLE
"aboutChoice": "string" throws an error on load of new samples config template file

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#294]
The About option in the samples config files is preset with the following:

```
        "restrictNavigation": false,
        "aboutChoice": "string",
        "help": {
            "folderName": "default"
        },
```

This throws and error after hitting the validate button because the "content" key is empty.

Should the files be preset with something like the following About key/value?

```
		"about": {
			"aboutChoice": "string",
			"content": "Insert About text here."
		}

```

**Comment by jolevesq** [comment]
Sample is for test only. Even if there is error inside the template it is not a problem.
