### ISSUE TITLE
Initialize repo framework

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpa-apgf#3]
- [x] Link to code climate
- [x] Link eslint (check if jscs is still used)
- [x] Link to travis
- [x] Link to node (npm)
- [x] Link to Webpack
- [ ] ? Vagrantfile
- [ ] ? devkey.enc
- [x] Link to reviewable

**Comment by jolevesq** [comment]
Use https://github.com/buzinas/tslint-eslint-rules for eslint rules with tslint

**Comment by jolevesq** [comment]
Good documentation for angular with webpack https://semaphoreci.com/community/tutorials/setting-up-angular-2-with-webpack

**Comment by jolevesq** [comment]
How to have hybrid angular solution: https://medium.com/@SevenLee/configuration-tips-to-build-hybrid-angular-1-and-angular-2-project-in-real-world-230b715629dc

Maybe overhead and should stick with Angular1 to work with schemaForm
