### ISSUE TITLE
Hyperlinks inside Help instructions open in same window/tab as authoring tool. The user looses all config settings when going back to authoring tool window.

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#306]
e.g.

Clicking the following 'spatial reference system' hyperlink in the Extents and Levels of detail Help section should open the link in a new window/tab.

> 2. You need to create one Spatial Extent set by Tile Schema. In this section you will define the spatial reference system to use
> 
> - To find which WKID to use you can refer to this [spatial reference list](http://spatialreference.org/ref/).
> - Enter a unique ID then set at least the default extent.

**Comment by jolevesq** [comment]
Do it for all url (inside help and link to github)
