### ISSUE TITLE
Create default value for all items in schema

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpa-apgf#32]
In the schema we need default values if we want the key to exist in the model out of the box withou the user having to enter a value first. This way even if a user save the edit wihout entering data in one of the section the default values will be present.

**Comment by ChrisLatRNCan** [comment]
Still have problems with default values that are objects or arrays.

**Comment by yblain** [comment]
The only default values that will be set will the the ones at the lowest level in the tree.

**Comment by jolevesq** [comment]
Will do as needed
