### ISSUE TITLE
Add cleanCanvas field to the export section of the  schema

### ISSUE THREAD

**Issue by Pewillia** [fgpv-vpgf/fgpa-apgf#420]
There is a cleanCanvas field in the export section of the latest version of the RAMP schema.

	                        "cleanCanvas": {"type": "boolean", "default": false, "description": "If set to true the export will omit layers and images that would cause issues with saving. If set to false users may need to save by right-clicking and selecting save image."}

**Comment by jolevesq** [comment]
Handle by #425
