### ISSUE TITLE
 TypeError: Cannot read property 'entries' of undefined    at setCollapsibleHeaderEntry (av-main.js:186524)

### ISSUE THREAD

**Issue by Pewillia** [fgpv-vpgf/fgpa-apgf#475]
setCollapsibleHeaderEntry error - TypeError: Cannot read property 'entries' of undefined.

This occurs when reading  the config.sample template that has a structure legend. The error occurs in the init routine of map.directive.js where setcollapsibleheader is called.

**Comment by jolevesq** [comment]
I close this because sample config was way behind our schema version and it may cause the error. if it happen with one of our new config file we can reopen the issue
