### ISSUE TITLE
Create project folder skeleton

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpa-apgf#5]
Using angular 1 or 2 to determine how to set up.

We need to do more research on Angular

**Comment by jolevesq** [comment]
We will use Angular 4

Those are Angular 4 seed projects
- https://github.com/AngularClass/angular-starter
- https://github.com/Plum-Crazy/angular-seed
     - [info](http://1904labs.com/2017/05/06/1399/)

**Comment by yblain** [comment]
After a bit of research it was determined that Angular 1 with Angular schemaform will be used including the same project structure as FGPV.
