### ISSUE TITLE
Special characters showing up in WMS form description text

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#503]
**Layer Entries** ×Close
 CBCT
**ID** 
 CBCT (success)
`The id of the layer entry in the WMS. The value between the <Name>...</Name> tag of the layer (e.g. <Name>roads</Name> where roads is the ID).
`

**Comment by jolevesq** [comment]
Humm, it works on my computer, https://dev.gcgeo.gc.ca/aut/index-en.html and https://s-bsc-geoappint.nrn.nrcan.gc.ca/fgpa/fgpa-new/samples/fgpv-author.html. It doesn't work on https://nronk1awvasp036.nrn.nrcan.gc.ca/fgpa/fgpa-latest/samples/fgpv-author.html.

Maybe something needs to be done on this server?

**Comment by bchagnon** [comment]
It does not work on s-bsc-geoappint for me:

![badcharacters](https://user-images.githubusercontent.com/2006029/68045016-f49dc480-fcae-11e9-99bf-2aaeb718ec5a.png)

They seam to be back space characters coded in the text string:

![badcharacters_BS](https://user-images.githubusercontent.com/2006029/68045177-4ba39980-fcaf-11e9-9559-a0495f265983.png)

**Comment by jolevesq** [comment]
Yes there is. We need them because if not <name> is escape from the string. I retry on appint and I have the problem now....

**Comment by bchagnon** [comment]
Could you use `&lt;` for '<' and `&gt;` for '>' instead, or maybe use some kind of `text` method to process the json value?

**Comment by jolevesq** [comment]
At the same time we have updated the code so the language selector will not appears if there is only one language inside the array of languages
