### ISSUE TITLE
link for help in plugin form

### ISSUE THREAD

**Issue by Pewillia** [fgpv-vpgf/fgpa-apgf#507]
The links for the help on the plug in  form don't open in a new tab.

**Comment by jolevesq** [comment]
What do you mean? There is a help section inside the plugin for and it opens like the other help sections. Can you add mote information?

**Comment by Pewillia** [comment]
The links for plugin documentation and information open up in the same window as the authoring tool and could open up in a new tab.  Because it opens up in the same tab  when you page back you loose the session .and have to reload any files.

For more information about core plugins. 
For more documentation about plugins.
