### ISSUE TITLE
Set extent broken on dev gcgeo

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#536]
Cannot set extents dynamically

> angular.js:12994 GET https://[hideservername]/aut/config/config-extent-3857.json 404 (Not Found)

**Comment by jolevesq** [comment]
The path was not good to open the set extent configuration file. This should be broken from the beginning. I have updated the path in preview-extent.html.

**Comment by jolevesq** [comment]
Merci pour l’info. C’est corrige… mauvais lien. Bizarre car le lien n’a jamais du fonctionner
