### ISSUE TITLE
Set Extent always sets min max values to same numbers

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#541]
After setting new extent with interactive pop-up map, min max values are always set to 
-2757989.363188633 -1608962.2562523577 6043790.264644251 3662114.943769528 when using the authoring tool on gcgeo dev site.

![set_extent](https://user-images.githubusercontent.com/2006029/84045839-51fda080-a977-11ea-8676-17abd48cda07.png)

**Comment by bchagnon** [comment]
Console error:

`https://dev.gcgeo.gc.ca/aut/extensions/extent.js 404 (Not Found)`

**Comment by jolevesq** [comment]
There is an extensiont file extent.js missing on the server. I do not have access to the server so I just hope we will be able to install the viewer the cloud soon

**Comment by jolevesq** [comment]
It will be fix when we will release the authoring tool on the cloud later in October. Solve by #557
