### ISSUE TITLE
Can't save file because of Legend Structured error message

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#544]
In ver. 1.2.0 [9862d737c] with legend set to Autopopulate, I get the following error message when trying to save my config file. Same message appears if I set legend to Structured and JSON format is valid.

`Error in Legend Structured section. Solve the issue before saving!`

**Comment by bchagnon** [comment]
Found the problem. The Services object in the file did not conform to 3.3.0 although it did not throw a validation error.

**Comment by jolevesq** [comment]
Is there something to add to the authoring tool to make sure this will not happen again?
