### ISSUE TITLE
area of interest limits on gcgeo

### ISSUE THREAD

**Issue by Pewillia** [fgpv-vpgf/fgpa-apgf#548]
Coordinates for area are not saved in version running on gcgeo

**Comment by jolevesq** [comment]
I have an open ticket for this, see https://github.com/fgpv-vpgf/fgpa-apgf/issues/541. It is because there is a missing js file on the server. We do not have access to EDC anymore so we will solve this when we will be in the cloud

**Comment by jolevesq** [comment]
Solve with the cloud
