### ISSUE TITLE
Repair chart plugins

### ISSUE THREAD

**Issue by jolevesq** [fgpv-vpgf/fgpa-apgf#550]
Since identify work with layer id, remove the layer id box. At the same time add the details section and find why the subscribe from chart plugin doesn't have the layer id. It works on the GitHub demo page but not from this apge.

**Comment by jolevesq** [comment]
Plus modification has been made to plugin config

**Comment by Pewillia** [comment]
can't load the examples chart plugins , they cause an error, can save but can't preview

**Comment by jolevesq** [comment]
The layer id not working is because the function was not available in version 3.2.0. Fixed when use version 3.3.1
