### ISSUE TITLE
Preview map is broken

### ISSUE THREAD

**Issue by bchagnon** [fgpv-vpgf/fgpa-apgf#585]
Console shows errors trying to reach cloud **dev** site when requesting fgpv files (.js, .css)

**Comment by jolevesq** [comment]
@bchagnon Cloud dev environment is down. Should be back in fews days.

**Comment by jolevesq** [comment]
@bchagnon dev is back up.... do you still have the problem?

**Comment by bchagnon** [comment]
LGTM now. Thank you.
