### ISSUE TITLE
FGP Viewer Author mock-ups

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpa-apgf#6]
Some ideas about Author UI
- Think about Bootstrap UI system while doing the mock up

- Viewer in a tab.

**Comment by ChrisLatRNCan** [comment]
Here some MockUps
![accueilauteur](https://user-images.githubusercontent.com/16193004/28032348-26f5edf2-6578-11e7-8258-8935e656b6e1.png)
![configmenu](https://user-images.githubusercontent.com/16193004/28032354-297713e4-6578-11e7-9e7e-29130be7b720.png)
![validateerror](https://user-images.githubusercontent.com/16193004/28032360-2f44ed5a-6578-11e7-82d3-a5fd493a29ec.png)
![validatevalid](https://user-images.githubusercontent.com/16193004/28032362-3187f9c2-6578-11e7-8948-d7d9ac34a6e5.png)
![validatepreview](https://user-images.githubusercontent.com/16193004/28032366-339bb258-6578-11e7-8e3e-51e7927e0dfb.png)
