### ISSUE TITLE
Initial list of basic features for FGP Viewer Author

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpa-apgf#7]

**Comment by ChrisLatRNCan** [comment]
**Work in progress**
List of possible features. Will need to be updated, sorted and cleaned. 

Category   |	Priority	| Description
------------ | ------------- | -------------
Asset | TBD | Bilingual UI
Feature | TBD | Create config file
Feature | TBD | Load and modify existing config file
Feature | TBD | Save config file
Feature | TBD | Map extent extraction tool
Feature | TBD | Form validation
Feature | TBD | Config file status (validation)
Feature | TBD | On the fly map rendering (included web services vizualisation)
Feature | TBD | Structured legend previzualisation
Feature | TBD | Default config file profil
Feature | TBD | Config files collection
Feature | TBD | Existing layers/basemaps list/collection
Feature | TBD | Batteries included project (config file + html template)

**Comment by yblain** [comment]
Will transform the list into issues before closing
