### ISSUE TITLE
Manage schema's versions

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpa-apgf#73]
Actually, we always work with the latest version of the viewer schema. As time goes by, other versions of it may appear. We need to develop a version managing process so user could edit/create config files corresponding to a particular version of the viewer/schema.

**Comment by jolevesq** [comment]
We should manage form version as well. To do so we should have our form inside their own file_version and the author will call the correct form the needed version.

**Comment by jolevesq** [comment]
When we upload a new file a validation should be made. Compare the file with the schema and add all missing node with default value and remove all node not present in the schema.
