### ISSUE TITLE
Update schema

### ISSUE THREAD

**Issue by ChrisLatRNCan** [fgpv-vpgf/fgpa-apgf#77]
update schema with those changes (get the latest):

https://github.com/fgpv-vpgf/fgpv-vpgf/commit/a7b80ecbaf5f35d3c8c2f129183eb93b549d9ae8#diff-76d5ffeac090c76ed5f4c581f02f3c53

https://github.com/fgpv-vpgf/fgpv-vpgf/commit/024651f2ba58e42ebded2a4e388798af44b52df1#diff-76d5ffeac090c76ed5f4c581f02f3c53

https://github.com/fgpv-vpgf/fgpv-vpgf/commit/a97c9a03ed8791699e8b74082b154432a83f0f54#diff-76d5ffeac090c76ed5f4c581f02f3c53

https://github.com/fgpv-vpgf/fgpv-vpgf/commit/803ad7696575a4bacba6e66efd38085aa4ca94b4#diff-76d5ffeac090c76ed5f4c581f02f3c53

https://github.com/fgpv-vpgf/fgpv-vpgf/commit/f40a3ac6bd8f6b8c14bd321b7ac9bda1050b7189#diff-76d5ffeac090c76ed5f4c581f02f3c53

https://github.com/fgpv-vpgf/fgpv-vpgf/commit/909f82daf9eec8812d2b428c7b988b67d56a5e97#diff-76d5ffeac090c76ed5f4c581f02f3c53

**Comment by jolevesq** [comment]
Wait for version 2.3.0
