### ISSUE TITLE
Document schema

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpa-apgf#8]

**Comment by ChrisLatRNCan** [comment]
_Work in progress_

**Strategy: convert the JSON schema to a github flavor markdown file**

There's no _one tool do it all_. The principal challenge here is the presence of $ref and cycles in the schema.
So, for the first draft the tool [jsonschema-md](https://github.com/joxoo/jsonschema-md) is used with manual editing.
However, I would like something more like [wetzel](https://github.com/AnalyticalGraphicsInc/wetzel).

**Improvements:**

- Integrate more doc attributes eg. _example_ or _linked image_ and _animated gif_.
- The items attributes don't show, so we can't link to the definitions. Will need to add a column called _item type_ with a link to the definition
- Make the required statement more like in [wetzel](https://github.com/AnalyticalGraphicsInc/wetzel)

**Comment by ChrisLatRNCan** [comment]
Cut schema into pieces [here](https://github.com/ChrisLatRNCan/fgpv-pgfv-schema)

**Comment by ChrisLatRNCan** [comment]
Idea:
https://blog.cloudflare.com/cloudflares-json-powered-documentation-generator/

**Comment by jolevesq** [comment]
Est-ce que tupeux ajouter le liens et un peu de doc a l<issue sur la documentation?

**Comment by jolevesq** [comment]
See #120
