### ISSUE TITLE
Choose schema to form technology

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpa-apgf#9]

**Comment by yblain** [comment]
Will eveluate  [Makinacorpus Schema Form](https://github.com/makinacorpus/angular2-schema-form) and [NG2 Schema form](https://github.com/udos86/ng2-dynamic-forms).

**Comment by ChrisLatRNCan** [comment]
Some observations:
[Makinacorpus Schema Form](https://github.com/makinacorpus/angular2-schema-form) 

- Doesn't yet support $ref (workaround: [json-schema-parser](https://github.com/izumin5210/json-schema-parser))


[NG2 Schema form](https://github.com/udos86/ng2-dynamic-forms)

- Needs a schema parser. Could probably use something like [json-schema-parser](https://github.com/izumin5210/json-schema-parser)

**Comment by ChrisLatRNCan** [comment]
Have same issue as [here](https://github.com/izumin5210/json-schema-parser/issues/1) with [json-schema-parser](https://github.com/izumin5210/json-schema-parser)

**Comment by ChrisLatRNCan** [comment]
To try
https://github.com/udos86/ng2-dynamic-forms/tree/development#json-export--import

**Comment by jolevesq** [comment]
I tried with this one and was not able to make it work yet in Angular 4: https://github.com/dschnelldavis/angular2-json-schema-form

**Comment by ChrisLatRNCan** [comment]
End the winner is [**angular-schema-form (AngularJS) with Bootstrap UI**](https://github.com/json-schema-form/angular-schema-form) at least for short to mid-term.
